name: CI_echemamr                                                                                                                                          
on: 
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  drivencavity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential g++ gfortran
    - name: AMReX
      run: |
         mkdir build
         git clone https://github.com/AMReX-Codes/amrex.git build/amrex
    - name: Build
      env:
         AMREX_HOME: ${GITHUB_WORKSPACE}/build/amrex
      working-directory: ./test/drivenCavity
      run: |
        make -j 2 COMP=gnu
    - name: Run
      working-directory: ./test/DriftDiffuse1d
      run: |
        ./echemAMR3d.gnu.MPI.ex inputs.2d
