name: CI_echemamr                                                                                                                                          
on: 
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  drivencavity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: System Dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential g++ gfortran libopenmpi-dev openmpi-bin
    - name: Build
      working-directory: ./test/drivenCavity
      run: |
        make -j 2 COMP=gnu
    - name: Run
      working-directory: ./test/DriftDiffuse1d
      run: |
        ./echemAMR3d.gnu.MPI.ex inputs.2d
